services:
  # vpn:
  #   container_name: vpn
  #   image: dperson/openvpn-client
  #   # cap_add, security_opt, and volume required for the image to function
  #   cap_add:
  #     - net_admin
  #   environment:
  #     - TZ=PST8PDT
  #     - VPN_AUTH=KS2-3032f11d14a42772081aeacf6fc63e10;Y7EupCuXrciR
  #     - FIREWALL=""
  #   networks:
  #     - media_server
  #   # if using '-d' or 'DNS' you can't enable the `read_only: true` option
  #   read_only: true
  #   tmpfs:
  #     - /run
  #     - /tmp
  #   restart: unless-stopped
  #   security_opt:
  #     - label:disable
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - /dev/net:/dev/net:z
  #     - ./vpn:/vpn

  gluetun:
    image: qmcgaw/gluetun:v3.40
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8090:8090
    environment:
      # - FIREWALL=off
      - UPDATER_PERIOD=24h
      - VPN_SERVICE_PROVIDER=custom
      - OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf
      - OPENVPN_CIPHERS=AES-256-CBC
      - OPENVPN_PORT=1197
      - OPENVPN_USER=$OPENVPN_USER
      - OPENVPN_PASSWORD=$OPENVPN_PASSWORD
    volumes:
      - /dev/net:/dev/net:z
      - ./gluetun:/gluetun
    networks:
      media_server:
    restart: unless-stopped

  qbit:
    image: linuxserver/qbittorrent:4.6.2
    container_name: qbit
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - WEBUI_PORT=8090
    volumes:
      - ./qbittorrent:/config
      - $MEDIADIR/torrents:/media/torrents
    network_mode: service:gluetun # run on the vpn network
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

networks:
  media_server:
