version: "3.5"

services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: unless-stopped
    volumes:
      - ./npm:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80 
      - 443:443
      - 81:81 
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

networks:
  default:
    name: media_server
    external: true

