version: "3.5"

services:
    goaccess:
        image: xavierh/goaccess-for-nginxproxymanager:latest
        container_name: goaccess
        restart: always
        ports:
            - 7880:7880
        environment:
            - TZ=$TZ
            - SKIP_ARCHIVED_LOGS=False #optional
            - DEBUG=False #optional
            - BASIC_AUTH=False #optional
            - EXCLUDE_IPS=127.0.0.1,192.168.0.1-192.168.0.100 #optional - comma delimited 
            - LOG_TYPE=NPM #optional - more information below
        volumes:
        - ./npm/logs:/opt/log
